version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: dockerfiles/dev/django/Dockerfile
    container_name: backend
    volumes:
      - .:/usr/src/app  # Mount the entire project directory into the container
    ports:
      - "8000:8000"  # Expose port 8000
    environment:
      - DEBUG=True  # Optional, but helpful for development
    env_file:
      - ./envs/dev/django/.env  # Load environment variables from the .env file

#       - DB_NAME=postgres
#       - DB_USER=postgres
#       - DB_PASSWORD=postgres
#       - DB_HOST=db
#       - DB_PORT=5432
#     depends_on:
#       - db  # Wait for db to be available

#   # PostgreSQL container
#   db:
#     image: postgres
#     container_name: db
#     environment:
#       - POSTGRES_DB=postgres
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#     volumes:
#       - postgres_data:/var/lib/postgresql/data  # Persist data across restarts
#     ports:
#       - "5432:5432"  # Expose port 5432 for PostgreSQL

# # Volumes to persist PostgreSQL data
# volumes:
#   postgres_data:
